name: CD
on: 
  pull_request:
    branches: [ feature/fix_lock_check ]
    type: [closed]

jobs:
  ecr_setting:
    # if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Mfa login
        uses: ./.github/actions/aws-mfa-login
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          mfa_key: ${{ secrets.MFA_KEY }}
          mfa_arn: ${{ secrets.MFA_ARN }}
        
      - id: get_ecr_password
        name: Get ECR password
        run: |
          PROIFLE_REGION=$(aws configure get region --profile mfa)
          ECR_PASSWORD=$(aws ecr get-login-password --region $PROIFLE_REGION --profile mfa)
          echo "ECR_PASSWORD=$ECR_PASSWORD" >> $GITHUB_OUTPUT
    outputs:
      ecr_password: ${{ steps.get_ecr_password.outputs.ECR_PASSWORD }}

  debian_build:
    needs: ecr_setting
    runs-on: ubuntu-latest
    container:
      image: 557571393534.dkr.ecr.ap-northeast-2.amazonaws.com/floom
      credentials:
        username: AWS
        password: ${{ needs.ecr_setting.outputs.ecr_password }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'flody_ws/etc/'

      - name: Checkout submodules
        run: |
          cd flody_ws/etc
          git submodule update --init --recursive
      - name: Generate debian file
        run: |
          source /opt/floatic/debian/humble/setup.bash
          cd flody_ws/etc
          floom-generate rosdebian
          ls debian_results/*.deb
        shell: bash
  
      - name: AWS Mfa login
        uses: ./flody_ws/etc/.github/actions/aws-mfa-login
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          mfa_key: ${{ secrets.MFA_KEY }}
          mfa_arn: ${{ secrets.MFA_ARN }}
      
      - name: Upload to S3
        run: |
          aws s3 cp $(ls flody_ws/etc/debian_results/*.deb) s3://robotics-workflow-archive/twist_mux/
